import pluginJs from "@eslint/js";
import spellchecker from "eslint-plugin-spellcheck";
import { globalIgnores } from "eslint/config";
import globals from "globals";
import tseslint from "typescript-eslint";

const skipWords = [
    "luna",
    "viewable",
    "enum",
    "WebLivenessCheck",
    "liveness-check",
    "webhookURL",
    "req",
    "otp",
    "kyc",
    "Blockchain",
    "usd",
    "Usd",
    "dto",
    "redis",
    "ttl",
    "Istoken",
    "transactional",
    "approver",
    "momo",
    "sms",
    "axios",
    "varchar",
    "pei",
    "nextstep",
    "mtn",
    "palmpay",
    "Acc",
    "Mfa",
    "liveness",
    "jsonb",
    "otu",
    "bitafrika",
    "gmail",
    "Naira",
    "Nigeria",
    "Ghana",
    "Cedi",
    "cancelled",
    "nullable",
    "blake2b512",
    "utf",
    "xss",
    "blake2digest",
    "Blake2",
    "generateBlake2Digest",
    "blake2",
    "Cashout",
    "cashouts",
    "msg",
    "formated",
    "ussd",
    "ghs",
    "buyrate",
    "sellrate",
    "Captcha",
    "xhash",
    "lhash",
    "otpauth",
    "totp",
    "multer",
    "pdf",
    "Deductable",
    "Evm",
    "usdt",
    "usdc",
    "eth",
    "remitafrika",
    "kycs",
    "Swappable",
    "iphone",
    "macintosh",
    "linux",
    "cros",
    "dec",
    "str",
    "num",
    "Uid",
    "Todays",
    "Airtel",
    "Tigo",
    "Telecel",
    "Vodafone",
    "cors",
    "urlencoded",
    "etag",
    "trx",
    "tusd",
    "bsc",
    "bnb",
    "nft",
    "datasource",
    "hcaptcha",
    "originalname",
    "jpeg",
    "incr",
    "passcode",
    "singlesends",
    "upsert",
    "errored",
    "facematch",
    "metamap",
    "gps",
    "biometric",
    "webhook",
    "eden",
    "nin",
    "signup",
    "stdout",
    "stderr",
    "argv",
    "hmac",
    "sid",
    "sdk",
    "firstname",
    "middlename",
    "mobilemoney",
    "ogateway",
    "accountquery",
    "txid",
    "lsig",
    "facebook",
    "whatsapp",
    "btc",
    "bch",
    "ltc",
    "doge",
    "matic",
    "nodemailer",
    "personalizations",
    "htmlbody",
    "tls",
    "Afrika",
    "kollet",
    "Ethereum",
    "Binance",
    "Polygon",
    "priv",
    "tnt",
];

/** @type {import('eslint').Linter.Config[]} */
export default [
    {
        files: ["src/**/*.{js,mjs,cjs,ts}"], // Limit linting to src only
        languageOptions: {
            globals: globals.node,
            parser: tseslint.parser,
        },
        plugins: {
            spellcheck: spellchecker,
        },
        rules: {
            "spellcheck/spell-checker": [
                "error",
                {
                    comments: false,
                    strings: true,
                    identifiers: true,
                    lang: "en_US",
                    skipWords: skipWords,
                    skipIfMatch: ["http://[^s]*"],
                    skipWordIfMatch: [
                        "^foobar.*$",
                        "^[-\\w]+\/[-\\w\\.]+$",
                        "^[a-f0-9]{24,64}$",
                        ".*type$",
                        ".*rc20$",
                        /^joi.*$/i,
                        "Zabcdefghijklmnopqrstuvwxyz0123456789",
                        /.*blake2.*/i,
                    ],
                    minLength: 3,
                },
            ],
        },
    },
    {
        files: ["src/**/*.{js,mjs,cjs}"],
        ...pluginJs.configs.recommended,
    },
    {
        files: ["src/**/*.{ts}"],
        ...tseslint.configs.recommended,
    },
    globalIgnores(["dist", "build"]),
];
